version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
    labels:
      - "dependencies"
      - "bot"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    groups:
      docker-updates:
        patterns:
          - "*"
    labels:
      - "docker"
      - "dependencies"