version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      prod-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@dotenvx/*"
          - "@esbuild-plugins/*"
          - "@tailwindcss/postcss"
          - "@types/*"
          - "drizzle-kit"
          - "esbuild"
          - "esbuild-node-externals"
          - "postcss"
          - "react-email"
          - "tailwindcss"
          - "tsc-alias"
          - "tsx"
          - "typescript"
          - "yargs"
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        patterns:
          - "@dotenvx/*"
          - "@esbuild-plugins/*"
          - "@tailwindcss/postcss"
          - "@types/*"
          - "drizzle-kit"
          - "esbuild"
          - "esbuild-node-externals"
          - "postcss"
          - "react-email"
          - "tailwindcss"
          - "tsc-alias"
          - "tsx"
          - "typescript"
          - "yargs"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      major-updates:
        update-types:
          - "major"
      minor-and-patch-updates:
        update-types:
          - "minor"
          - "patch"
