version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "patch"
          - "minor"
          
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      updates:
        update-types:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/install"
    schedule:
      interval: "daily"
    groups:
      updates:
        update-types:
          - "patch"
          - "minor"
