    next-router:
      tls:
        certResolver: letsencrypt
        domains:
          - main: "example.com" # REPLACE THIS WITH YOUR DOMAIN
            sans:
              - "*.example.com" # REPLACE THIS WITH YOUR DOMAIN
