name: Create Dev-Image

on:
  pull_request:
    branches:
      - main
      - dev
    types: 
      - opened
      - synchronize
      - reopened

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:


      - uses: actions/github-script@v8
        env:
          REPO: https://hub.docker.com/r/${{ secrets.DOCKER_HUB_REPO }}/tags
          DEV_PR: ${{ secrets.DOCKER_HUB_REPO }}:dev-pr${{ github.event.pull_request.number }}
          DEV_PR_PG: ${{ secrets.DOCKER_HUB_REPO }}:postgresql-dev-pr${{ github.event.pull_request.number }}
        with:
          script: |
            const repo = process.env.REPO;
            const devPr = process.env.DEV_PR;
            const devPrPg = process.env.DEV_PR_PG;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for your PR!  
              Dev images for this PR are now available on [docker hub](${repo}):
              \`\`\`
              ${devPr}
              \`\`\`
              \`\`\`
              ${devPrPg}
              \`\`\``
            })
