name: Create Dev-Image

on:
  pull_request:
    branches:
      - main
      - dev
    types: 
      - opened
      - draft

jobs:
    release:
        name: Build and Release Dev-Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker images
              run: |
                  docker buildx build --build-arg DATABASE=sqlite --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKER_HUB_REPO }}:dev-pr${{ github.event.pull_request.number }} --push .
                  docker buildx build --build-arg DATABASE=pg --platform linux/arm64,linux/amd64 -t ${{ secrets.DOCKER_HUB_REPO }}:postgresql-dev-pr${{ github.event.pull_request.number }} --push .
