name: Create Dev-Image

on:
  pull_request:
    branches:
      - main
      - dev
    types: 
      - opened
      - draft

jobs:
    release:
        name: Build and Release Dev-Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and push Docker image SQL
              uses: docker/build-push-action@v5
              with:
                  platforms: linux/amd64
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_REPO }}:dev-pr${{ github.event.pull_request.number }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_REPO }}:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_REPO }}:buildcache,mode=max
                  build-args: DATABASE=sqlite
                  
            - name: Build and push Docker image PG
              uses: docker/build-push-action@v5
              with:
                  platforms: linux/amd64
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_REPO }}:postgresql-dev-pr${{ github.event.pull_request.number }}
                  cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_REPO }}:buildcache
                  cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_REPO }}:buildcache,mode=max
                  build-args: DATABASE=pg
                  
