on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Delete PR Docker image
        run: |
          IMAGE="your-docker-org/your-image"
          TAG="dev-pr${{ github.event.pull_request.number }}"
          echo "Deleting $IMAGE:$TAG ..."
          curl -s -X DELETE \
            -u "${{ secrets.DOCKER_HUB_USERNAME }}:${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/$IMAGE/tags/$TAG/"